
<div class="entry-content">
    <div class="bgtfw ">
        <div class="boldgrid-section">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 col-xs-12 col-sm-12">
                        <h1 class=""><strong>Terms and Conditions (Point of Sales (POS) System)</strong></h1>
                        <p class=""><strong>PLEASE READ THESE TERMS AND CONDITIONS VERY CAREFULLY</strong></p>
                        <p class="">PLEASE READ THESE TERMS AND CONDITIONS VERY CAREFULLY. THE TERMS AND CONDITIONS OF PRODUCT SALES AND SERVICE ARE LIMITED TO THOSE CONTAINED HEREIN AND THOSE WITHIN THE PURCHASE ORDER. ANY ADDITIONAL OR DIFFERENT TERMS OR CONDITIONS IN ANY FORM DELIVERED BY YOU (“BUYER”) ARE HEREBY DEEMED TO BE MATERIAL ALTERATIONS AND NOTICE OF OBJECTION TO THEM AND REJECTION OF THEM IS HEREBY GIVEN.</p>
                        <p class="">BY MAKING AN ORDER FOR PRODUCTS OR SERVICES FROM NICHE PEAK (“SELLER”) BUYER AGREES TO BE BOUND BY AND ACCEPTS THESE TERMS AND CONDITIONS. THESE TERMS AND CONDITIONS CONTROL ALL FUTURE PURCHASES BY BUYER, EVEN IF BUYER DOES NOT SIGN A PURCHASE ORDER AT THE TIME OF SUCH SUBSEQUENT PURCHASE. IF BUYER AND SELLER SIGNED A SEPARATE AGREEMENT THAT AGREEMENT SHALL CONTROL ONLY WITH RESPECT TO THE PRODUCTS PURCHASED THERE-UNDER. ALL NEW PRODUCT PURCHASED FROM SELLER SHALL BE GOVERNED BY THESE TERMS AND CONDITIONS.</p>
                        <p class="">These Terms and Conditions constitute a binding contract between BUYER and SELLER (as defined in the Purchase Order) and are referred to herein as either “Terms and Conditions” or this “Agreement”. BUYER accepts these Terms and Conditions by placing an order with SELLER through a Purchase Order.</p>
                        <p class=""><strong>1) Purchase Price:&nbsp;</strong>BUYER agrees to pay SELLER the price for the Products, including any required down payment, in the amount and in accordance with the payment terms set forth in the Purchase Order. Any change in the number of users, sites or system configurations must be requested to&nbsp;SELLER not less than 30 days before such change and may require the payment of additional fees.&nbsp;SELLER may in its discretion provide updates for the Hardware or Software at no additional charge in conjunction with selected Services, or charge an additional fee for such updates.</p>
                        <p class=""><strong>2) Taxes:</strong>&nbsp;All prices and charges for Products provided hereunder are exclusive of any taxes applicable to the transaction, such as value added taxes, sales or use taxes, duties, or other taxes or levies imposed by any government, public authority, or government agency on&nbsp;BUYER’s purchase of the Products hereunder, all of which are the responsibility of&nbsp;BUYER to pay, provided, for avoidance of doubt, that&nbsp;BUYER shall not be responsible for payment of any taxes based on the income, property or employment of employees by SELLER. In the event SELLER is ever assessed or threatened to be assessed taxes, fees, levies, penalties and/or fines regarding BUYER’s failure to pay any taxes applicable to the transaction, BUYER authorizes SELLER to submit an payment draft for the amount claimed due from BUYER.</p>
                        <p class=""><strong>3) Cancellation/Return Policy:&nbsp;</strong><em>IN NO EVENT WILL RETURNS BE ALLOWED FOR ANY EQUIPMENT SOLD TO BUYER. BUYER ACKNOWLEDGES UPON EXECUTION OF THE PURCHASE ORDER SELLER PURCHASES ANY EQUIPMENT FROM THIRD PARTIES AND SUCH EQUIPMENT IS REGISTERED IN BUYER’S NAME AND THEREFORE NON-REFUNDABLE.</em></p>
                        <p class=""><strong>a) Cancellation.</strong>&nbsp;In the event BUYER cancels BUYER’s order prior to delivery of the Products SELLER will refund to BUYER within ninety days the amount of BUYER’s deposit LESS expenses incurred by SELLER on this project the reasons provided in this Section.</p>
                        <p class=""><strong>b) Hardware Returns.&nbsp;</strong>Subject to SELLER’s approval, BUYER may return Hardware, if BUYER notifies SELLER in writing of such desire to return within 7 days of the date of delivery of the Products. In the event SELLER accepts BUYER’s request for return and BUYER returns the Hardware to SELLER in new condition, SELLER shall provide BUYER a credit of the original purchase price on SELLER’s account that BUYER may use for purchase of any other available Products requested by BUYER. In the event BUYER returns the Hardware to SELLER in less than new condition, SELLER will determine, at SELLER’s sole discretion, whether to accept and what credit shall be given for the return. If SELLER does not accept the return BUYER shall have no claim against SELLER.</p>
                        <p class=""><strong>c) Software Returns:&nbsp;</strong>Software License Fees, Labor and Services. NO REFUND WILL BE GIVEN FOR ANY software provided BUYER or prepaid software license fees or labor provided, expended or committed to BUYER. BUYER shall have no claim against SELLER for any other refunds or damages.</p>
                        <p class="">BUYER ACKNOWLEDGES THAT PRIOR TO DELIVERY OF THE PRODUCTS, SELLER EXPENDS SUBSTANTIAL AMOUNT OF TIME AND MONEY IN THE CONFIGURATION OF THE PRODUCTS ORDERED FOR BUYER, which includes but is not limited to purchasing equipment, configuring the Software for BUYER’s specific use, converting BUYER’s data to make it compatible with the Products,&nbsp; and to configure and test the Products. AS SUCH BUYER AGREES THE TERMS OF THIS CANCELLATION/RETURN POLICY ARE REASONABLE.</p>
                        <p class=""><strong>4) Delivery &amp; Installation:</strong>&nbsp;SELLER shall ship products to BUYER within FOUR WEEKS FROM RECEIPT OF THE PURCHASE ORDER AND PAYMENT OF THE PURCHASE PRICE SPECIFIED IN THE PURCHASE ORDER IS MADE. BUYER understands that all Hardware purchases must be paid (as specified in PO) prior to shipment of the Hardware to BUYER. On-site work (if any is contracted for) will follow BUYER’S receipt of Hardware components by approximately two weeks and must be paid if full two weeks prior to SELLER scheduling such work. Either party may notify the other of complications arising with these dates and will at that time reschedule. Exact delivery time cannot be guaranteed.</p>
                        <p class=""><strong>a) Site Preparation:&nbsp;</strong>The BUYER shall prepare the site for installation and render all reasonable assistance during implementation of the system. Such site preparations&nbsp;shall include tested and certified cabling, conduit, power point, dedicated phone lines and suitably placed furnishing for the efficient and effective implementation and installation. The SELLER shall not be liable for any damages caused by deficiency in site preparation except when such deficiency is caused solely by SELLER negligence.</p>
                        <p class=""><strong>b) Training:&nbsp;</strong>The SELLER shall provide basic training for the operation of the system as specified in PURCHASE ORDER.&nbsp; The BUYER shall accept the training to have been completed satisfactorily upon BUYER acceptance of the system. The SELLER reserves the rights to charge a fee for any additional training or support requested after&nbsp;BUYER acceptance of the system.&nbsp;</p>
                        <p class=""><strong>c) Acceptance:&nbsp;</strong>The BUYER shall acknowledge acceptance of the system (hardware &amp; software) after SELLER installation through the acceptance of the DELIVERY ORDER and/or issuance of INVOICE.</p>
                        <p class=""><strong>5) Grant of Software License:</strong></p>
                        <p class="">Upon payment of the monthly License Subscription Fee detailed in the Purchase Order, SELLER grants to BUYER a month to month, nontransferable and nonexclusive license to use the Software (“Software”) (to wit, the computer program with its supporting documentation). This license shall apply to any&nbsp;enhancements and updates to the Software acquired by BUYER from SELLER. This license is made available to BUYER on the condition that the BUYER fulfills all of their relevant obligations arising out of this Agreement including but not limited to the following:</p>
                        <p class=""><strong>a) Term:&nbsp;</strong>This is a month to month license. Payment of the License Subscription Fee is due in advance of each month. SELLER’s receipt of such payment grants BUYER an additional one month term of the license. When the balance of prepaid License Subscription Fee are exhausted, BUYER’s software license term will automatically expire and the Software will cease to function for BUYER and any data stored by this Software will be unavailable to BUYER. BUYER may terminate the license by giving SELLER 30 days written notice via electronic mail to the address of sales@nichepeak.com. SELLER will acknowledge receipt of termination request via return electronic mail to BUYER. SELLER may terminate this license at any time if BUYER fails to comply with any of the terms of this Agreement or for SELLER’s convenience upon 30 days written notice to BUYER. Within five (5) days after termination of the Agreement, BUYER will return to SELLER the Software and all copies thereof (including, without limitation, partial copies or modifications), and supporting documentation in BUYER’s possession or control.</p>
                        <p class=""><strong>b) Deactivation:&nbsp;</strong>Upon termination of this Agreement, SELLER may interfere with, suspend, or terminate BUYER’s use of and access to the Software at no liability to SELLER.</p>
                        <p class=""><strong>c) Use:&nbsp;</strong>This license authorizes BUYER to use the Software only for BUYER’s own use on a single computer system at the installation address designated in the Purchase Order or such other location to which BUYER may relocate in the future provided that BUYER shall give SELLER prompt written notice of the address change. SELLER will not be responsible for, and will not provide support for Software which has been modified by the BUYER in any manner other than authorized tailoring to the single computer system as explained in the supporting documentation of the Software.</p>
                        <p class=""><strong>d) Updates:&nbsp;</strong>SELLER may advise BUYER of enhancements and updates to Software. BUYER may obtain such updates or enhancements, as they become available upon terms and for the amounts then in effect as set by SELLER. SELLER may, at its sole discretion, provide enhancements and upgrades free of charge. All enhancements and updates to the Software provided by SELLER are subject to the terms of this Agreement.</p>
                        <p class=""><strong>e) Copies:&nbsp;</strong>BUYER shall NOT COPY THE Software FOR ANY PURPOSE. BUYER shall not use or obtain any Software that has been copied, purchased or obtained from any other means, person or entity other than a SELLER.</p>
                        <p><strong>f) Transfer.&nbsp;</strong>BUYER may not rent, lease, lend or sublicense the Software.</p>
                        <p class=""><strong>g) Proprietary Rights:</strong></p>
                        <p class="">BUYER recognizes and acknowledges that the Software (including, without limitation, the computer program and user manual, together with all copies, enhanced versions or updates thereof) are and shall remain the property of SELLER. BUYER acknowledges and agrees the ideas and expressions contained in the Software and user manuals, and the nonpublic information disclosed to BUYER in the course of the Services are confidential proprietary information and trade secrets of SELLER (“Confidential Information”). BUYER agrees&nbsp;to hold the Confidential Information in confidence and agrees not to transfer, dispose of, publish, display, disclose or otherwise make available in any fashion the Confidential Information. BUYER is responsible for and agrees to pay SELLER for any damages or losses due to the unauthorized copying or disclosure of the Software. BUYER recognizes that unauthorized copying or disclosure of the Software will cause irreparable injury to SELLER and that SELLER shall be entitled to, among other things, enjoin BUYER from any such activities.</p>
                        <p class=""><strong>h) Notices:&nbsp;</strong>All applicable rights in patents, copyrights, trademarks and trade secrets in the Software are and will remain in SELLER. In order to protect trademark, trade name, trade secret and copyright or patent rights of SELLER in the Software, BUYER agrees not to remove, change or tamper with any notices on any Software product.</p>
                        <p class=""><strong>6) Limited Hardware Warranty:</strong>&nbsp;SELLER WARRANTS THAT DURING THE FIRST TWELVE MONTHS FOLLOWING SHIPMENT OF THE HARDWARE TO BUYER, THE HARDWARE WILL BE FREE OF DEFECTS IN MATERIALS AND WORKMANSHIP (“HARDWARE WARRANTY PERIOD”). BUYER acknowledge that BUYER’s selection of any particular Hardware is based on BUYER’s own evaluation of the requirements of BUYER’s business and BUYER’s evaluation of the functions, capacities and specifications of the Products selected. SELLER does not warrant that the Products will meet all or any of BUYER’s requirements or any requirements imposed by BUYER.</p>
                        <p class=""><strong>7) Hardware Support:</strong>&nbsp;If the Hardware is discovered to contain a defect in materials or workmanship during the Hardware Warranty Period SELLER will provide Hardware repair/replacement service support on any Hardware supplied by SELLER which failed during normal use. During this Hardware Warranty Period BUYER shall not be responsible for the cost of labor and parts in the repair/replacement of such Hardware.&nbsp;BUYER will be responsible for the cost of shipping and other out of pocket expenses made by SELLER. This support is limited to assistance in the repair or replacement of only Hardware provided by SELLER. This provision does not cover damage resulting from acts of God, flood, lightning, malicious software, BUYER’S negligence, alterations, mishandling, BUYER’s improper installation, or BUYER’s failure to protect such Hardware.SELLER shall have the sole discretion to either repair the Hardware or replace it. In the course of providing such support, SELLER may use new or serviceable parts that are equivalent to new in performance. SELLER will ship replacement or loan Hardware as promptly as such Hardware is available and will expedite repairs on failed Hardware so as to minimize downtime for BUYER. However in no event will SELLER be liable for loss of business, profits or any other damages to BUYER during the time it takes SELLER to repair or replace the Hardware. The foregoing is BUYER’S sole remedy for Hardware failures supplied by SELLER in the first twelve months following deliver. Notwithstanding anything above SELLER will not be obligated to initiate or perform and Hardware repair/replacement service support if any license granted to BUYER by SELLER has been suspended, terminated, canceled or is otherwise impaired or if BUYER is in breach of any provision of these Terms and Provision.</p>
                        <p class="">Following the Hardware Warranty Period SELLER, at SELLER’s discretion may provide hardware repair support to BUYER for the duration of the license granted by SELLER at a fee determined solely by SELLER. In no event however, will SELLER be required to replace any Hardware after the end of the Hardware Warranty Period. However in no event will SELLER be&nbsp;liable for loss of business, profits or any other damages to BUYER during the time it takes SELLER to repair or replace the Hardware.</p>
                        <p><strong>8) Limited Software Warranty:</strong></p>
                        <p class="">Limited Software Warranty: The Software is provided to BUYER with a limited warranty as set forth herein. Subject to Section 9 of this Agreement, SELLER WARRANTS THE SOFTWARE MANUFACTURED BY SELLER TO BE FREE FROM DEFECTS DURING THE SUBSCRIPTION TERM. SHOULD BUYER’S SOFTWARE CONTAIN A DEFECT, UPON WRITTEN NOTIFICATION OF THE DEFECT AND SELLER’s DETERMINATION THAT THE DEFECT IS COVERED UNDER THIS LIMITED SOFTWARE WARRANTY, WHICH DETERMINATION IS IN SELLER’s SOLE DISCRETION, SELLER WILL CORRECT THIS DEFECT WITHIN NINETY (90) DAYS. IN THE EVENT SELLER IS UNABLE TO CORRECT THE DEFECT IN THE NINETY (90) DAY PERIOD THEN UPON RETURN OF ALL SOFTWARE AND MANUALS TO SELLER; SELLER WILL WITHIN THIRTY (30) DAYS REFUND TO BUYER ALL LICENSE SUBSCRIPTION FEES PAID BY BUYER DURING THE PRIOR NINETY (90) DAY PERIOD. BUYER AGREES THAT A PERCEIVED LACK OF FEATURES AND/OR DISSATISFACTION WITH PROGRAM FLOW, FUNCTION, SPEED AND/OR PROCEDURES WITH THE SOFTWARE DOES NOT CONSTITUTE AN ERROR AND ARE NORMAL CHARACTERISTICS OF SOFTWARE. BUYER ACCEPTS COMPLETE LIABILITY FOR DATA LOSS OR DISTORTION FROM ANY AND ALL MEANS. SOFTWARE IS WITHOUT WARRANTY OF ANY KIND FOR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. SELLER DOES NOT GUARANTEE CONTINUED ELECTRONIC COMMUNICATION ABILITY WITH VENDORS AS VENDOR’S COMMUNICATION SPECIFICATIONS MAY CHANGE OR BE REVOKED BY VENDORS.</p>
                        <p class=""><strong>9) Software Support:</strong>&nbsp;SELLER will provide premium software support via telephone and Internet remote connection on first come; first served basis provided BUYER’S License Subscription Fee is current. Support is typically available 9:00 AM to 5:00 PM Pacific Time zone Monday through Friday (except holidays). After hours and weekend emergency support plans are available for additional monthly cost. SELLER has no obligation to provide support for software other than that is manufactured by SELLER and DOES NOT provide support on issues related to or stemming from computer viruses, spy-ware, Windows updates and/or ad-ware.</p>
                        <p class=""><strong>10) Limitations on Hardware and Software Warranty:</strong>&nbsp;SELLER does not warrant that BUYER’s operation of the Hardware or Software will be uninterrupted or error free. BUYER assumes the responsibility to take adequate precautions against damages to BUYER’s operation that could be caused by such interruptions or errors. In addition to the limitations described in other Sections of this Agreement, the limited Hardware and Software Warranty will not apply to Hardware or Software that has (i) been serviced, modified, repaired or altered by anyone other than SELLER, (ii) has not been installed or maintained by BUYER or a third party in accordance with SELLER’s requirements, and (iii) has been subjected to electrical stress, power fluctuations, improper or unauthorized use or negligence, acts of God or malicious software.</p>
                        <p class=""><strong>11) Back-up Subscription:</strong>&nbsp;BUYER may, at an additional monthly fee add any one or more additional available back-up subscriptions from SELLER.&nbsp; SELLER makes no representation or warranties that the operation of the backup will be uninterrupted or error free.&nbsp; SELLER shall not be liable to BUYER for any loss of BUYER’s content or data for any reason that may be related to such back-ups.</p>
                        <p><strong>12) Limitation of Liability:</strong></p>
                        <p class="">Limitation of Liability. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL SELLER, SELLER’S SHAREHOLDERS, EMPLOYEES/AGENTS OR ITS SUPPLIERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS OR CONFIDENTIAL OR OTHER INFORMATION, FOR BUSINESS INTERRUPTION, FOR PERSONAL INJURY, FOR LOSS OF PRIVACY, FOR FAILURE TO MEET ANY DUTY INCLUDING OF GOOD FAITH OR OF REASONABLE CARE, FOR NEGLIGENCE, AND FOR ANY OTHER PECUNIARY OR OTHER LOSS WHATSOEVER) ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OF OR INABILITY TO USE THE PRODUCTS, THE FAILURE TO PROVIDE SUPPORT SERVICES, OR UNDER OR IN CONNECTION WITH ANY PROVISION OF THESE TERMS AND CONDITIONS, EVEN IN THE EVENT OF THE FAULT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, BREACH OF CONTRACT OR BREACH OF WARRANTY OF SELLER, SELLER’S SHAREHOLDERS, EMPLOYEES/AGENTS OR ANY SUPPLIER, AND EVEN IF SELLER, SELLER’S SHAREHOLDERS, EMPLOYEE/AGENTS OR ANY SUPPLIER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL OUR LIABILITY IN CONNECTION WITH THIS AGREEMENT EXCEED THE AGGREGATE AMOUNT BUYER ACTUALLY PAID SELLER UNDER THE TERMS OF THIS AGREEMENT DURING THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM AGAINST US.</p>
                        <p class=""><strong>13) Future Expansion:</strong>&nbsp;Any Products requested by BUYER in the future will be based on prices in effect at that time.</p>
                        <p class=""><strong>14) Training / Unwarranted Repair:</strong>&nbsp;If SELLER is requested to train and/or tutor employees (beyond SELLER’S standard initial demonstration of functionality), BUYER shall pay for these services based on prices of SELLER in effect at that time. If SELLER is requested to repair Hardware or Software that is not covered under the warranties provided in this Agreement BUYER shall pay for these services based on prices of SELLER in effect at that time.</p>
                        <p class=""><strong>15) AutoPay:</strong></p>
                        <p class=""><strong>a)&nbsp;SELLER&nbsp;</strong>will automatically debit BUYER’s contracted monthly License Subscription Fees on or about the 14th of each month for the following month’s license. All other purchases will be detailed on an invoice electronically mailed to BUYER and will detail the amount that was debited.</p>
                        <p class=""><strong>b)&nbsp;BUYER&nbsp;</strong>shall review each statement for BUYER’s AUTOPAY account. If BUYER believes an incorrect charge has been incurred, BUYER must notify SELLER of such disputed charges within thirty days of the first statement on which the charge first appears or BUYER waives BUYER’s right to dispute the charge. If BUYER informs SELLER that an error exists on BUYER’s statement, SELLER will attempt to correct that error prior to BUYER’s next statement.</p>
                        <p class=""><strong>c)&nbsp;BUYER&nbsp;</strong>may hold up or stop an electronic fund transfer provided BUYER gives SELLER notice of at least three business days before the scheduled transfer date and provides SELLER with an acceptable alternative form of AUTOPAY. SELLER shall bear no liability or responsibility for any losses of any kind that BUYER may incur as a result of any delay in the actual date on which BUYER’s account is debited.</p>
                        <p class=""><strong>d)&nbsp;If any changes&nbsp;</strong><strong>occur&nbsp;</strong>in the information on BUYER’s AUTOPAY application, BUYER must immediately notify SELLER in writing of such changes. If BUYER either does not notify SELLER in writing of such changes or does so in an untimely fashion SELLER shall bear no liability or responsibility for any losses incurred to the extent permitted by law. SELLER’S sole liability to BUYER shall be SELLER’S obligation to make any appropriate changes once in receipt of BUYER’s written notification. The actual settlement date (date funds are transferred from BUYER’s checking or savings account or charged to BUYER’s credit card) will be the due date of BUYER’s bill.</p>
                        <p class=""><strong>e)&nbsp;SELLER&nbsp;</strong>reserves the right to change these conditions at any time. Notice may be given on or with BUYER’s bill or by other methods. Either party may terminate this agreement at any time by giving the other party written notice reasonably in advance of the next scheduled settlement date. Termination shall not prevent a debit transaction authorized before any notice of termination. Termination will limit duration of Software Licenses granted to the period of time covered by pre-paid rents.</p>
                        <p class=""><strong>f)&nbsp;BUYER&nbsp;</strong>agrees to be bound by any rules BUYER’s financial institution requires for pre-authorized electronic funds transfer. SELLER suggests that BUYER check with BUYER’s financial institution to see if there are any fees associated with the pre-authorized payment option.</p>
                        <p class=""><strong>g)&nbsp;BUYER’s&nbsp;</strong>Subscription License Fee AUTOPAY will begin the month before BUYER receives BUYER’s Products because the Subscription License Fee is paid in advance of the month it’s for. Should shipping of BUYER’s new system be delayed past the 1st day of the Subscription month,&nbsp;SELLER will promptly refund the Software License Fee for the period of the 1st through BUYER’s system ship date.</p>
                        <p class=""><strong>16) Notice of Commercial Product:</strong>&nbsp;Notice of Commercial Product:The goods and services provided by SELLER to BUYER under this Agreement are not consumer products and are therefore not governed by consumer product laws.</p>
                        <p class="">&nbsp;</p>
                        <p class=""><strong>17) Metadata and DataWarehousing:</strong>&nbsp;As an additional condition of use by BUYER of SELLER’s goods and services, BUYER acknowledges and agrees that SELLER may collect and warehouse electronic data and other information relating to BUYER’s purchases and sales through BUYER’s use of SELLER’s software. The purpose of collecting this data is to compile real time information about sales, retail pricing and customer purchasing trends within specific geographic boundaries to drive business intelligence dashboards of how BUYER’s business compares to the group.</p>
                        <p class="">BUYER agrees SELLER may share this information with BUYER and other customers of SELLER provided SELLER does not disclose identification of BUYER or BUYER’s customers and vendors, including but not limited to names, addresses and phone numbers to anyone other than BUYER’s supplier(s).</p>
                        <p class=""><strong>18) Miscellaneous:</strong></p>
                        <p class=""><strong>a) Assignment.&nbsp;</strong>BUYER may not assign any of the rights, interests, or obligations under this Agreement without the prior written consent of SELLER.</p>
                        <p class=""><strong>b) Notices.&nbsp;</strong>BUYER consents to receiving electronic records, which may be provided via a Web browser or e-mail application connected to the Internet; individual BUYERS may withdraw consent to receiving electronic records or have the record provided in non-electronic form by contacting SELLER. In addition, Internet connectivity requires access services from an Internet access provider. Electronic signatures (or copies of signatures sent via electronic means) are the equivalent of written and signed documents.</p>
                        <p><strong>c) Time of Essence.&nbsp;</strong>Time is of the essence with respect to all dates and time periods set forth or referred to in this Agreement.</p>
                        <p class=""><strong>d)&nbsp;Governing Law.&nbsp;</strong>This Agreement will be governed by and construed in accordance with the laws of the state, without regard to conflict-of-laws principles. Any action or proceeding seeking to enforce any provision of this Agreement or based on any right arising out of this Agreement must be brought against any of the parties in Court of the State, subject to applicable jurisdictional requirements, and each of the parties consents to the jurisdiction of such courts (and of the appropriate appellate courts) in any such action or proceeding and waives any objection to such venue.</p>
                        <p class=""><strong>e) Attorney Fees.</strong>If&nbsp;SELLER has to retain an attorney to interpret or enforce the provisions of this Agreement, to rescind this Agreement, or otherwise with respect to the subject matter of this Agreement, even if an arbitration, suit, or action is not instituted, the SELLER will be entitled to recover from BUYER with respect to such issue, in addition to costs, reasonable attorney fees incurred in the consultation, preparation, prosecution, or defense of such issue.</p>
                        <p class=""><strong>f) Entire Agreement.&nbsp;</strong>These Terms and Conditions, together with the Purchase Order (and including the documents and instruments referred to in this Agreement) and any modifications as set forth below constitute the complete and exclusive agreement and understanding of the parties with respect to the subject matter of this Agreement and supersedes all prior understandings and agreements, whether written or oral, among the parties with respect to such subject matter. This Agreement may not be explained or supplemented by any prior course of dealings or trade by custom or usage.</p>
                        <p class=""><strong>g) Modification.</strong>&nbsp;SELLER reserves the right to make changes to these Terms and Conditions at any time upon 30 days written notice to BUYER. Upon such change&nbsp;BUYER shall have the right to terminate this Agreement. Any use of the products or services by&nbsp;BUYER after 30 days or after such notice shall be deemed to constitute acceptance by BUYER of such modifications.</p>
                        <p class=""><strong>h) Severability:&nbsp;</strong>If any provision contained in this Agreement is or becomes invalid, illegal or unenforceable in whole or in part, such invalidity, illegality, or unenforceability shall not affect the remaining provisions and portions of this Agreement, and the invalid, illegal, or unenforceable provision shall be deemed modified so as to have the most similar result that is valid and enforceable under law.</p>
                        <p class=""><strong>i) Survival:&nbsp;</strong>Section 2., Taxes, 5b)., Deactivation, 5e)., Copies, 5f)., Transfer, 5g)., Proprietary Rights, 5h)., Notices, 11., Limitation of Liability, 15., Notice of Commercial Product, and 16., Miscellaneous shall survive the termination of this Agreement for any reason.</p>
                        <p><strong>j) Definitions.</strong></p>
                        <p class="">“Hardware” means the tangible equipment supplied by SELLER to BUYER in accordance with the Purchase Order.</p>
                        <p class="">“Products” mean Hardware, Software and related services provided by SELLER. “Purchase Order” means a request by BUYER for the license and purchase of Products that is accepted by SELLER.</p>
                        <p class="">“Services” means labor provided to BUYER, in configuring and setting up Products from BUYER and additional service described in the Purchase Order or this Agreement.</p>
                        <p class="">“Software” means the programs, data and related manuals supplied by SELLER to BUYER in accordance with the Purchase Order. “Subscription License Fee” means the monthly fee payable to SELLER for the license to use the Software in accordance with this Agreement.</p>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- .bgtfw container -->
</div><!-- .entry-content -->